### ISSUE TITLE
Chaining methods -- only first dot

### ISSUE THREAD

**Issue by Manaus** [btwael/mammouth#59]
With the latest version, 3.0.1, I get an error when trying to chain methods, like 

    matches = page.images.find("selector").not("selector") 
    // $matches = $page->images->find("selector")->not("selector");

Looks like the parser is halting at the first dot...

**Comment by btwael** [comment]
The problem here is that `not` is a mammouth reserved words so it's not allowed to use it as property or identifier. So maybe you can change `not` in your library. [see this](http://mammouth.wamalaka.com/#try:%3Cp%3E{{%0Amatches%20%3D%20page.images.find%28%22selector%22%29.noti%28%22selector%22%29%0A}}%3C%2Fp%3E)
However I will try to add support for reserved words as proprties and class functions
Thank you for reporting!
